language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python manage.py collectstatic --noinput
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: D+UFxocGeoKi/8vL4IGInbzyDNRGz0OoxkTg2YmK5bxjo57thVhmG6SCf7EVx2fdTus7d7AW16sCezZiFe4y0EClqc6vE7Pr3qSAjsQbIaRctsjSspA1QvdzVH32vx7NLBbwPwZXzPJ1T+TNKtHPO28G0VvYLH4kG8FEuhOhMrx7RC+YYOV4GQTqYilF1RHhfWZtQ3QAiuv9/5Q6CYQCyCRLgylUwCpJNqKYEODVBwmB5lXIWbhayvYH3HQ9nwvmnSjkB6IDDWJzs/JKtD2BunsNWvwoQYVh/4VzRnRX2oLX2ip4oCqI3NkPc7JcbHgZKTBKpyPyUKqBZDCfZelM+OZtDm6jNO+46AYtpw1gxhubKNxamsChOV6hFeg0lUXI/gnidhYHskAW/8ezs0TAD75OTlTOlWE5wg5Oi1h5qgl1scksSWT51bl3+5JNdkhapJPnZIrDT65sh0galdbjg+NZB2TEfywVifUGE4j/DtVQ8hdcuNw2yZ+GEhYlaPqjmwR49oxqDjWWbgauIeQtvTkctiT52OtKfXUBkBBAHqRMhVQbk/xX/BHqeuf+416jZaajxv9p6rQzdXFgmgKBfdFwpA+rl8xoRzGc/TcVdL9IhM+Pwng339iE8TPohxnosY45PQN2aQyrYP14PxyvsxUjVg4m0/iLSnRN3itaN24=
  app: tb-mysite
  on:
    repo: tomboo/mysite
