language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python manage.py collectstatic --noinput
- python manage.py test
deploy:
  provider: heroku
  app: tb-mysite
  api_key:
    secure: kO7sX8139vuDbJGYamcxX5quSnTAhEQuzmgJMwdiVTUdopwoqqDuR+xmrjji5XUwFinRbri3Z/jtQAmr7AF2OVez047QNqKM/meY41tFkKoCWxaWL2B1UP1zleP71OtOe4urPj+36NPbV9x617JK0tAxfXSaetkIPamghgz54hel/UjeZ9F5i4q1/XLBsSLC5Zv1muviawXjK7IpvTmHU/ixV1jpZnnxALLQq/h+coYF1I1UAuXkrTahCOpk6C7Fep5fWQzrx06niAS1aGk1jxpFmsqGAkWQf6F1QM+u3Pc4GzAqeLC2m0HmKIr/OASghlvzfvKQDNZQLf/lB4k0oiEDpwrGZlhPpJ70boD2mWPzgLk3So1JvABIuaj0k8dwfOdoWd1jRbt5iVq1mzhaSEWq2UJliflkRnAw5RuL3v0twtsPEcU4W/XVafXGPOGVInWGe7zr0pkyR5ihcpMv8KhBj2vmmuvtgM7ATVnRPTN1Gz+V71eiLS6XySf4ggo7c0nsDqavBra3HKFtzhllTuG6/gIGhUXsdlrvNCR0K5bqKRFThb9F4a2beIkw1/wI2TFhCLE4ojabfRdRO83MKcyjP5mNexEr9j8+cTmw2ibFvyxNWkXTQuHYdyaMjHFjJ7S/BB7vBPb8lT1wpoygxvmo3WRyqLp06c/1W6yR1JQ=
