language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python manage.py collectstatic --noinput
- python manage.py test
deploy:
  provider: heroku
  app: tb-mysite
  api_key:
    secure: sKmntSAB6Nj8lc1QQkewzkRHOz8k/0ZWAg2qQLYTpxAR3xn+rq8YaB5F91UMGDuu/SJQTEiU0Y/E4utO1dtxOOCbemZeTr0vxVsyLA7fgW8yLQ7twM6qlkr9z/TYge7IL58WDmPmeLy83qIwFSS/koeR9uXxcVJiRkFwN4pyGIrQnCn3FYZ4Og4/wUMsBcLmhH3TFQQUBCw4R1ZcII9M4j8WUP+DUyCeqN2TjLFaJ7HG/3luDWwEw3XHaqKY2uIym083VoZ3F7GbruMAepCs9QjwDOI1uroR+fcq/9F8yPySMurOeYZ3/tgHrX78zaRc4JPD3L/UJ4F8v91xnT9XrK3saNvQ1VCTJcTLS3CF1N+6sZkpHvT46lR9PjrWIx56fYjKLit+hIZ2xZbvAiamwXGX/jm59le3mmp+U8G85O8tGq1HcZzOaTRTpr6oXOsj/zBOf79e9JYQdxPhRnNzJlzW8Bv1NiR0afZld7fTvs86hIw8Ys0Wvj+wyW6GTLRqnZHwIBu5NRO5RUv7D6o5MhOU6NFB8vpngZ8g7JTU6iJFpmALKAXHQCAIBdJIMK+aqhB0ZzOh7oRyUaQX/5mwxSSJeYfei9qq1pvxioxEARr/rCjsFq5kFySfGQX5zMF/yT7ldicolfBUyK7SbVv1TY8l+d9+LGEKPsUYDE1ms0A=
