# Generated by Django 2.1.1 on 2018-09-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='diastolic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='systolic',
            field=models.IntegerField(),
        ),
    ]
